title: OpenCluster
description: Simulating the software behind the Automotive dashboard.

theme: jekyll-theme-cayman

show_downloads: false

github:
  repository_url: https://github.com/Tife28/open-cluster-sim
